package sex.erp.android;

import android.app.*;
import android.content.res.ColorStateList;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.*;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.io.InputStream;
import java.util.function.Consumer;

/** Website-style native sheet; selecting one image does not grant album access. */
final class ChatImageUploadSheet {
    static Dialog show(Activity a,NativeApi api,ThemePalette p,JSONObject me,String match,Consumer<Consumer<Uri>> pick,Consumer<JSONObject> accepted,Runnable closed){
        Dialog dialog=new Dialog(a);LinearLayout root=column(a);root.setBackground(bg(a,p.surface,24,p.border,false));root.setPadding(dp(a,20),dp(a,18),dp(a,20),dp(a,16));
        LinearLayout header=new LinearLayout(a);header.setGravity(Gravity.CENTER_VERTICAL);TextView title=label(a,"发送图片",21,p.text);title.setTypeface(null,1);header.addView(title,new LinearLayout.LayoutParams(0,-2,1));FrameLayout close=new FrameLayout(a);close.addView(new SiteIconView(a,"close",p.muted,false),new FrameLayout.LayoutParams(dp(a,20),dp(a,20),Gravity.CENTER));close.setContentDescription(UiStrings.t("关闭"));close.setOnClickListener(v->dialog.dismiss());header.addView(close,new LinearLayout.LayoutParams(dp(a,40),dp(a,40)));root.addView(header);
        ScrollView scroll=new ScrollView(a);LinearLayout content=column(a);scroll.addView(content);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
        FrameLayout picker=new FrameLayout(a);picker.setBackground(bg(a,p.surface2,16,p.border,true));ImageView preview=new ImageView(a);preview.setScaleType(ImageView.ScaleType.FIT_CENTER);picker.addView(preview,new FrameLayout.LayoutParams(-1,-1));LinearLayout placeholder=column(a);placeholder.setGravity(Gravity.CENTER);placeholder.addView(new SiteIconView(a,"image_plus",p.muted,false),new LinearLayout.LayoutParams(dp(a,32),dp(a,32)));placeholder.addView(label(a,"选择图片",14,p.muted));placeholder.addView(label(a,"JPEG / PNG / WebP / GIF · 最多 20 MB",12,p.muted));for(int i=0;i<placeholder.getChildCount();i++){View child=placeholder.getChildAt(i);if(child instanceof TextView)((TextView)child).setGravity(Gravity.CENTER);}picker.addView(placeholder,new FrameLayout.LayoutParams(-1,-1));spaced(a,content,picker,180);picker.setContentDescription(UiStrings.t("选择图片"));
        spaced(a,content,label(a,"上传时会清除图片中继资料。",12,p.muted),-2);
        CheckBox real=check(a,"这是真人照片",p);spaced(a,content,real,-2);content.addView(label(a,"真人照片只能标为全年龄，NSFW 内容只能是 VRC 截图。",12,p.muted));spaced(a,content,label(a,"内容分级 *",15,p.text),-2);
        String[] values={"general","suggestive","r18"},names={"全年龄","擦边","R18"},descriptions={"日常照、合照","泳装、内衣、暗示姿势","裸露、性行为"};String[] rating={""},kind={""};Uri[] selected={null};boolean[] busy={false},active={true};int[] generation={0};boolean originalAllowed=feature(me,"chat_original_image"),restricted=false;JSONArray limits=me==null?null:me.optJSONArray("featureLimits");if(limits!=null)for(int i=0;i<limits.length();i++)restricted|="upload_nsfw".equals(limits.optString(i));final boolean limited=restricted;
        LinearLayout ratings=new LinearLayout(a);ratings.setBaselineAligned(false);Button[] choices=new Button[3];for(int i=0;i<3;i++){choices[i]=button(a,UiStrings.t(names[i])+"\n"+UiStrings.t(descriptions[i]),p,false);choices[i].setTextSize(12);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(a,72),1);lp.rightMargin=i<2?dp(a,8):0;ratings.addView(choices[i],lp);}spaced(a,content,ratings,-2);
        LinearLayout kinds=new LinearLayout(a);Button sexual=button(a,UiStrings.t("成人内容"),p,false),gore=button(a,UiStrings.t("血腥内容"),p,false);kinds.addView(sexual,new LinearLayout.LayoutParams(0,dp(a,44),1));kinds.addView(gore,new LinearLayout.LayoutParams(0,dp(a,44),1));spaced(a,content,kinds,-2);CheckBox adult=check(a,"我确认内容中的角色均为成年人",p);content.addView(adult);
        Switch original=new Switch(a);original.setText(UiStrings.t("发送原图"));original.setTextColor(p.text);original.setEnabled(originalAllowed);spaced(a,content,original,-2);content.addView(label(a,originalAllowed?"关闭时按普通聊天图片尺寸上传，开启时保留较高分辨率":"此功能需要网站相应会员权限",12,p.muted));CheckBox pledge=check(a,"我确认内容非儿童色情且非真人 NSFW，否则会导致账号限制或者封号。",p);android.text.SpannableString pledgeText=new android.text.SpannableString(pledge.getText());String pledgeString=pledgeText.toString();int nsfw=pledgeString.indexOf("NSFW");if(nsfw>=0)pledgeText.setSpan(new android.text.style.ForegroundColorSpan(p.accent),nsfw,nsfw+4,0);pledge.setText(pledgeText);spaced(a,content,pledge,-2);
        TextView status=label(a,limited?"此账号仅支持全年龄附件":"",12,p.muted);spaced(a,content,status,-2);LinearLayout footer=new LinearLayout(a);footer.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);Button cancel=button(a,UiStrings.t("取消"),p,false),upload=button(a,UiStrings.t("上传并发送"),p,true);footer.addView(cancel,new LinearLayout.LayoutParams(dp(a,80),dp(a,44)));LinearLayout.LayoutParams ulp=new LinearLayout.LayoutParams(dp(a,120),dp(a,44));ulp.leftMargin=dp(a,12);footer.addView(upload,ulp);View divider=new View(a);divider.setBackgroundColor(p.border);spaced(a,root,divider,1);spaced(a,root,footer,-2);
        Runnable update=()->{boolean generalOnly=limited||real.isChecked();if(generalOnly&&!"general".equals(rating[0]))rating[0]="";for(int i=0;i<3;i++){choices[i].setEnabled(!busy[0]&&(!generalOnly||i==0));choices[i].setAlpha(choices[i].isEnabled()?1:.4f);choices[i].setBackground(bg(a,p.surface,16,values[i].equals(rating[0])?p.accent:p.border,false));}boolean r18="r18".equals(rating[0]);kinds.setVisibility(r18?View.VISIBLE:View.GONE);adult.setVisibility(r18?View.VISIBLE:View.GONE);sexual.setTextColor("sexual".equals(kind[0])?p.accent:p.text);gore.setTextColor("gore".equals(kind[0])?p.accent:p.text);boolean valid=ChatImagePolicy.valid(selected[0]!=null,rating[0],real.isChecked(),limited,pledge.isChecked(),kind[0],adult.isChecked());upload.setEnabled(valid&&!busy[0]);upload.setAlpha(upload.isEnabled()?1:.45f);picker.setEnabled(!busy[0]);real.setEnabled(!busy[0]);pledge.setEnabled(!busy[0]);adult.setEnabled(!busy[0]);sexual.setEnabled(!busy[0]);gore.setEnabled(!busy[0]);original.setEnabled(originalAllowed&&!busy[0]);cancel.setEnabled(!busy[0]);close.setEnabled(!busy[0]);dialog.setCancelable(!busy[0]);};
        picker.setOnClickListener(v->pick.accept(uri->{if(!active[0])return;selected[0]=uri;placeholder.setVisibility(View.GONE);preview.setImageDrawable(null);int revision=++generation[0];update.run();new Thread(()->{Bitmap bitmap=null;try{BitmapFactory.Options options=new BitmapFactory.Options();options.inJustDecodeBounds=true;try(InputStream in=a.getContentResolver().openInputStream(uri)){BitmapFactory.decodeStream(in,null,options);}options.inJustDecodeBounds=false;options.inSampleSize=1;while(Math.max(options.outWidth,options.outHeight)/options.inSampleSize>1000)options.inSampleSize*=2;try(InputStream in=a.getContentResolver().openInputStream(uri)){bitmap=BitmapFactory.decodeStream(in,null,options);}if(bitmap!=null)bitmap=ImageOrientation.upright(a,uri,bitmap);}catch(Exception|OutOfMemoryError ignored){}Bitmap result=bitmap;a.runOnUiThread(()->{if(active[0]&&revision==generation[0]){preview.setImageBitmap(result);if(result==null)status.setText(UiStrings.t("图片预览不可用"));}else if(result!=null)result.recycle();});},"chat-upload-preview").start();}));
        for(int i=0;i<3;i++){int index=i;choices[i].setOnClickListener(v->{rating[0]=values[index];update.run();});}sexual.setOnClickListener(v->{kind[0]="sexual";update.run();});gore.setOnClickListener(v->{kind[0]="gore";update.run();});for(CheckBox cb:new CheckBox[]{real,adult,pledge})cb.setOnCheckedChangeListener((v,on)->update.run());cancel.setOnClickListener(v->dialog.dismiss());upload.setOnClickListener(v->{if(busy[0])return;busy[0]=true;update.run();status.setText(UiStrings.t("正在上传…"));JSONObject options=NativeApi.json("rating",rating[0],"realPerson",real.isChecked(),"original",original.isChecked());if("r18".equals(rating[0]))try{options.put("r18Kind",kind[0]);options.put("adultConfirm",adult.isChecked());}catch(JSONException ignored){}api.upload(a,selected[0],"chat_image",match,options,(response,error)->{if(!active[0])return;if(error!=null){busy[0]=false;status.setText(error.getMessage());update.run();}else{accepted.accept(NativeApi.object(response));dialog.dismiss();}});});dialog.setOnDismissListener(d->{active[0]=false;closed.run();});dialog.setContentView(root);dialog.show();Window w=dialog.getWindow();if(w!=null){w.setBackgroundDrawableResource(android.R.color.transparent);w.setGravity(Gravity.BOTTOM);w.setLayout(-1,Math.min(dp(a,680),a.getResources().getDisplayMetrics().heightPixels-dp(a,60)));}update.run();return dialog;
    }
    private static boolean feature(JSONObject me,String name){JSONObject features=me==null?null:me.optJSONObject("features"),value=features==null?null:features.optJSONObject(name);return value!=null&&value.optBoolean("enabled");}
    private static CheckBox check(Activity a,String title,ThemePalette p){CheckBox v=new CheckBox(a);v.setText(UiStrings.t(title));v.setTextColor(p.text);v.setTextSize(14);v.setButtonTintList(new ColorStateList(new int[][]{{android.R.attr.state_checked},{}},new int[]{p.accent,p.border}));return v;}
    private static LinearLayout column(Activity a){LinearLayout v=new LinearLayout(a);v.setOrientation(1);return v;}
    private static TextView label(Activity a,String text,int size,int color){TextView v=new TextView(a);v.setText(UiStrings.t(text));v.setTextSize(size);v.setTextColor(color);return v;}
    private static Button button(Activity a,String text,ThemePalette p,boolean primary){Button v=new Button(a);v.setText(text);v.setAllCaps(false);v.setTextColor(primary?Color.WHITE:p.text);v.setTextSize(14);v.setStateListAnimator(null);v.setBackground(bg(a,primary?p.accent:p.surface,24,primary?p.accent:p.border,false));return v;}
    private static GradientDrawable bg(Activity a,int color,int radius,int border,boolean dash){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(a,radius));if(dash)d.setStroke(dp(a,1),border,dp(a,4),dp(a,3));else d.setStroke(dp(a,1),border);return d;}
    private static void spaced(Activity a,LinearLayout parent,View child,int height){LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,height<0?height:dp(a,height));lp.topMargin=dp(a,16);parent.addView(child,lp);}
    private static int dp(Activity a,int n){return Math.round(n*a.getResources().getDisplayMetrics().density);}
}
