package sex.erp.android;

import android.app.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.*;
import android.view.Gravity;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.util.function.Consumer;

/** Native attachment preview and the website's explicit content-rating choices. */
final class MediaUploadForm {
    static Dialog show(Activity activity,NativeApi api,ThemePalette palette,JSONObject me,Uri uri,String purpose,String match,File local,Consumer<JSONObject> accepted,Consumer<NativeApi.Failure> failure,Runnable closed){
        boolean chatImage="chat_image".equals(purpose),postImage="post_image".equals(purpose),image=chatImage||postImage,originalAllowed=false,limited=false;
        if(me!=null){JSONObject features=me.optJSONObject("features"),feature=features==null?null:features.optJSONObject("chat_original_image");originalAllowed=feature!=null&&feature.optBoolean("enabled");JSONArray limits=me.optJSONArray("featureLimits");if(limits!=null)for(int i=0;i<limits.length();i++)if("upload_nsfw".equals(limits.optString(i)))limited=true;}
        final boolean restricted=limited;
        ScrollView scroll=new ScrollView(activity);LinearLayout content=new LinearLayout(activity);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(activity,18),dp(activity,12),dp(activity,18),dp(activity,12));content.setBackgroundColor(palette.surface);scroll.addView(content);
        final boolean[] active={true},uploading={false};final Handler ui=new Handler(Looper.getMainLooper());final android.media.MediaPlayer[] player={null};
        if(image){ImageView preview=new ImageView(activity);preview.setScaleType(ImageView.ScaleType.FIT_CENTER);preview.setBackgroundColor(palette.image);content.addView(preview,new LinearLayout.LayoutParams(-1,dp(activity,180)));new Thread(()->{try{BitmapFactory.Options options=new BitmapFactory.Options();options.inJustDecodeBounds=true;try(InputStream in=activity.getContentResolver().openInputStream(uri)){BitmapFactory.decodeStream(in,null,options);}options.inJustDecodeBounds=false;options.inSampleSize=1;while(Math.max(options.outWidth,options.outHeight)/options.inSampleSize>720)options.inSampleSize*=2;Bitmap bitmap;try(InputStream in=activity.getContentResolver().openInputStream(uri)){bitmap=BitmapFactory.decodeStream(in,null,options);}if(bitmap!=null)bitmap=ImageOrientation.upright(activity,uri,bitmap);final Bitmap result=bitmap;ui.post(()->{if(active[0])preview.setImageBitmap(result);else if(result!=null)result.recycle();});}catch(Exception|OutOfMemoryError ignored){ui.post(()->{if(active[0])preview.setContentDescription("图片预览不可用");});}},"attachment-preview").start();
        }else{Button play=new Button(activity);play.setAllCaps(false);play.setText("▶ 试听语音");play.setOnClickListener(v->{try{if(player[0]!=null){player[0].release();player[0]=null;play.setText("▶ 试听语音");return;}player[0]=new android.media.MediaPlayer();player[0].setDataSource(activity,uri);player[0].setOnPreparedListener(p->{if(!active[0])return;p.start();play.setText("■ 停止试听");});player[0].setOnCompletionListener(p->{p.release();player[0]=null;play.setText("▶ 试听语音");});player[0].setOnErrorListener((p,what,extra)->{p.release();player[0]=null;play.setText("无法试听，可重新选择文件");return true;});player[0].prepareAsync();}catch(Exception error){if(player[0]!=null){player[0].release();player[0]=null;}play.setText("无法试听，可重新选择文件");}});content.addView(play);}
        TextView hint=label(activity,image?"JPEG / PNG / WebP / GIF · 最多 20 MB":"语音长度为 1 秒至 2 分钟",12,palette.muted);hint.setPadding(0,dp(activity,10),0,dp(activity,10));content.addView(hint);
        CheckBox real=new CheckBox(activity);real.setText("这是真人照片");real.setTextColor(palette.text);if(image)content.addView(real);
        TextView legend=label(activity,"内容分级 *",14,palette.text);legend.setPadding(0,dp(activity,10),0,dp(activity,8));content.addView(legend);
        String[] ratings={"general","suggestive","r18"},names={"全年龄","擦边","R18"};String[] rating={""},kind={""};Button[] choices=new Button[3];LinearLayout row=new LinearLayout(activity);row.setOrientation(LinearLayout.HORIZONTAL);content.addView(row);
        LinearLayout kinds=new LinearLayout(activity);kinds.setOrientation(LinearLayout.HORIZONTAL);Button sexual=new Button(activity),gore=new Button(activity);sexual.setAllCaps(false);gore.setAllCaps(false);sexual.setText("成人内容");gore.setText("血腥内容");kinds.addView(sexual,new LinearLayout.LayoutParams(0,-2,1));kinds.addView(gore,new LinearLayout.LayoutParams(0,-2,1));kinds.setVisibility(android.view.View.GONE);content.addView(kinds);
        CheckBox adult=new CheckBox(activity);adult.setText("我确认内容中的角色均为成年人");adult.setTextColor(palette.text);adult.setVisibility(android.view.View.GONE);content.addView(adult);
        Switch original=new Switch(activity);original.setText("发送原图");original.setTextColor(palette.text);original.setEnabled(originalAllowed);if(chatImage){content.addView(original);TextView explanation=label(activity,originalAllowed?"关闭时按普通聊天图片尺寸上传，开启时保留较高分辨率":"此功能需要网站相应会员权限",11,palette.muted);content.addView(explanation);}
        TextView status=label(activity,restricted?"此账号仅支持全年龄附件":"请选择正确分级后上传",12,palette.muted);status.setPadding(0,dp(activity,10),0,0);content.addView(status);
        AlertDialog dialog=new AlertDialog.Builder(activity).setTitle(postImage?"添加照片":image?"发送图片":"发送语音").setView(scroll).setPositiveButton(postImage?"上传并添加":"上传并发送",null).setNegativeButton("取消",null).create();
        dialog.setOnDismissListener(d->{active[0]=false;if(player[0]!=null){player[0].release();player[0]=null;}if(local!=null)local.delete();closed.run();});dialog.show();Button upload=dialog.getButton(AlertDialog.BUTTON_POSITIVE);upload.setEnabled(false);
        Runnable update=()->{boolean generalOnly=restricted||(image&&real.isChecked());if(generalOnly&&!rating[0].equals("general"))rating[0]="";for(int i=0;i<3;i++){choices[i].setEnabled(!uploading[0]&&(!generalOnly||i==0));choices[i].setAlpha(choices[i].isEnabled()?1:.4f);GradientDrawable bg=new GradientDrawable();bg.setColor(ratings[i].equals(rating[0])?palette.surface2:palette.surface);bg.setCornerRadius(dp(activity,12));bg.setStroke(dp(activity,2),ratings[i].equals(rating[0])?palette.accent:palette.border);choices[i].setBackground(bg);}boolean r18=image&&"r18".equals(rating[0]);kinds.setVisibility(r18?android.view.View.VISIBLE:android.view.View.GONE);adult.setVisibility(r18?android.view.View.VISIBLE:android.view.View.GONE);sexual.setTextColor("sexual".equals(kind[0])?palette.accent:palette.muted);gore.setTextColor("gore".equals(kind[0])?palette.accent:palette.muted);upload.setEnabled(!uploading[0]&&!rating[0].isEmpty()&&(!r18||(!kind[0].isEmpty()&&adult.isChecked())));};
        for(int i=0;i<3;i++){final int index=i;Button choice=new Button(activity);choice.setText(names[i]);choice.setTextColor(palette.text);choice.setTextSize(13);choice.setAllCaps(false);choice.setPadding(dp(activity,4),0,dp(activity,4),0);choices[i]=choice;LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(activity,48),1);lp.rightMargin=i==2?0:dp(activity,6);row.addView(choice,lp);choice.setOnClickListener(v->{rating[0]=ratings[index];update.run();});}
        sexual.setOnClickListener(v->{kind[0]="sexual";update.run();});gore.setOnClickListener(v->{kind[0]="gore";update.run();});adult.setOnCheckedChangeListener((v,on)->update.run());real.setOnCheckedChangeListener((v,on)->{status.setText(on?"真人图片仅支持全年龄分级":"请选择正确分级后上传");update.run();});update.run();
        upload.setOnClickListener(v->{if(uploading[0])return;uploading[0]=true;real.setEnabled(false);original.setEnabled(false);sexual.setEnabled(false);gore.setEnabled(false);adult.setEnabled(false);update.run();if(player[0]!=null){player[0].release();player[0]=null;}status.setText("正在上传…");JSONObject options=NativeApi.json("rating",rating[0]);try{if(image){options.put("realPerson",real.isChecked());options.put("original",original.isChecked());if("r18".equals(rating[0])){options.put("r18Kind",kind[0]);options.put("adultConfirm",adult.isChecked());}}}catch(JSONException ignored){}
            api.upload(activity,uri,purpose,match,options,(response,error)->{if(!active[0])return;if(error!=null){uploading[0]=false;real.setEnabled(true);original.setEnabled(image&&me!=null&&featureEnabled(me,"chat_original_image"));sexual.setEnabled(true);gore.setEnabled(true);adult.setEnabled(true);status.setText(error.getMessage());update.run();failure.accept(error);}else{accepted.accept(NativeApi.object(response));dialog.dismiss();}});
        });
        return dialog;
    }
    private static boolean featureEnabled(JSONObject me,String key){JSONObject features=me.optJSONObject("features"),feature=features==null?null:features.optJSONObject(key);return feature!=null&&feature.optBoolean("enabled");}
    private static int dp(Activity activity,int n){return Math.round(n*activity.getResources().getDisplayMetrics().density);}
    private static TextView label(Activity activity,String value,int size,int color){TextView label=new TextView(activity);label.setText(value);label.setTextSize(size);label.setTextColor(color);return label;}
}
