package sex.erp.android;

import android.app.Dialog;
import android.content.Context;
import android.graphics.Bitmap;
import android.graphics.Color;
import android.graphics.drawable.GradientDrawable;
import android.os.Handler;
import android.os.Looper;
import android.text.InputFilter;
import android.text.TextWatcher;
import android.text.Editable;
import android.view.Gravity;
import android.view.View;
import android.view.Window;
import android.widget.Button;
import android.widget.EditText;
import android.widget.HorizontalScrollView;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.Switch;
import android.widget.TextView;
import org.json.JSONArray;
import org.json.JSONObject;
import java.io.ByteArrayOutputStream;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Set;

/** Native controls for the site's four share-card presets. */
final class ShareCardDialog {
    interface Actions { void save(byte[] png);void share(byte[] png,String url);void copy(byte[] png);void postX(String url);void copyLink(String url);void setPreview(byte[] png);void error(NativeApi.Failure failure);void message(String value); }
    private final MainActivity activity;private final NativeApi api;private final ThemePalette theme;private final JSONObject me;private final Actions actions;private final Handler handler=new Handler(Looper.getMainLooper());
    private final Dialog dialog;private final LinearLayout content;private final Map<String,ShareCardRenderer.Config> configs=new LinkedHashMap<>();private final ArrayList<JSONObject> photos=new ArrayList<>();private final Set<String> triedPhotos=new HashSet<>();private final Map<String,Bitmap> images=new HashMap<>();
    private JSONObject profile;private String format="og";private ImageView preview;private TextView status;private Runnable saveTask;private int renderGeneration;
    ShareCardDialog(MainActivity activity,NativeApi api,ThemePalette theme,JSONObject me,Actions actions){this.activity=activity;this.api=api;this.theme=theme;this.me=me;this.actions=actions;dialog=new Dialog(activity);content=new LinearLayout(activity);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(16),dp(12),dp(16),dp(20));content.setBackground(round(theme.surface,20));}
    void show(){ScrollView scroll=new ScrollView(activity);scroll.addView(content);dialog.setContentView(scroll);dialog.show();Window window=dialog.getWindow();if(window!=null){window.setBackgroundDrawableResource(android.R.color.transparent);window.setGravity(Gravity.BOTTOM);window.setLayout(-1,Math.min(dp(800),activity.getResources().getDisplayMetrics().heightPixels-dp(45)));}dialog.setOnDismissListener(d->{if(saveTask!=null){handler.removeCallbacks(saveTask);saveTask.run();saveTask=null;}handler.removeCallbacksAndMessages(null);for(Bitmap bitmap:images.values())if(bitmap!=null&&!bitmap.isRecycled())bitmap.recycle();});load();}
    private int dp(int value){return Math.round(value*activity.getResources().getDisplayMetrics().density);}
    private GradientDrawable round(int color,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));return d;}
    private TextView text(String value,int size,int color){TextView t=new TextView(activity);t.setText(value);t.setTextSize(size);t.setTextColor(color);return t;}
    private void add(LinearLayout target,View view){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.bottomMargin=dp(10);target.addView(view,p);}
    private LinearLayout column(){LinearLayout l=new LinearLayout(activity);l.setOrientation(1);return l;}
    private LinearLayout row(){LinearLayout l=new LinearLayout(activity);l.setGravity(Gravity.CENTER_VERTICAL);return l;}
    private Button button(String value,Runnable click,boolean selected){Button b=new Button(activity);b.setText(value);b.setTextSize(12);b.setAllCaps(false);b.setMinHeight(dp(35));b.setPadding(dp(7),0,dp(7),0);b.setTextColor(selected?Color.WHITE:theme.text);GradientDrawable background=round(selected?theme.accent:theme.surface2,11);if(!selected)background.setStroke(dp(1),theme.border);b.setBackground(background);b.setOnClickListener(v->click.run());return b;}
    private void section(String value){TextView title=text(value,14,theme.text);title.setTypeface(null,1);add(content,title);}
    private void load(){content.removeAllViews();status=text(UiStrings.t("正在加载分享名片…"),14,theme.muted);add(content,status);String id=me.optString("id");api.call("GET","/profiles/"+NativeApi.encode(id),null,(data,error)->{if(!dialog.isShowing())return;if(error!=null){status.setText(UiStrings.t("名片加载失败"));actions.error(error);return;}profile=NativeApi.object(data);if(profile.optJSONObject("profile")!=null)profile=profile.optJSONObject("profile");collectPhotos();api.call("GET","/me/share-cards",null,(saved,problem)->{if(!dialog.isShowing())return;if(problem!=null){status.setText(UiStrings.t("分享配置加载失败"));actions.error(problem);return;}JSONObject presets=NativeApi.object(saved).optJSONObject("presets");for(String name:ShareCardRenderer.FORMATS)configs.put(name,ShareCardRenderer.Config.read(name,presets==null?null:presets.optJSONObject(name)));drawControls();});});}
    private void collectPhotos(){photos.clear();Set<String> seen=new HashSet<>();JSONObject cover=profile.optJSONObject("cover");addPhoto(cover,seen);JSONArray list=profile.optJSONArray("photos");if(list!=null)for(int i=0;i<list.length();i++)addPhoto(list.optJSONObject(i),seen);addPhoto(profile.optJSONObject("avatar"),seen);}
    private void addPhoto(JSONObject photo,Set<String> seen){if(photo==null)return;String id=photo.optString("id");if(id.isEmpty()||seen.contains(id)||!"image".equals(photo.optString("kind","image"))||!"general".equals(photo.optString("rating","general"))||"rejected".equals(photo.optString("reviewState"))||"hide".equals(photo.optString("view")))return;seen.add(id);photos.add(photo);}
    private ShareCardRenderer.Config config(){return configs.get(format);}
    private String photoId(){String id=config().photoId;if(!id.isEmpty())for(JSONObject photo:photos)if(id.equals(photo.optString("id")))return id;return photos.isEmpty()?"":photos.get(0).optString("id");}
    private String url(){String value=NativeApi.ORIGIN+"/s/"+NativeApi.encode(me.optString("id"));String invite=me.optString("inviteCode");return config().invite&&!invite.isEmpty()?value+"?invite="+NativeApi.encode(invite):value;}
    private void changed(){preview();if(saveTask!=null)handler.removeCallbacks(saveTask);String selected=format;JSONObject snapshot=config().json();saveTask=()->{saveTask=null;api.call("PUT","/me/share-cards/"+selected,snapshot,(result,error)->{if(dialog.isShowing()&&error!=null){status.setText(UiStrings.t("分享配置未能保存，请重试"));actions.error(error);}});};handler.postDelayed(saveTask,800);}
    private void drawControls(){content.removeAllViews();LinearLayout header=row();TextView title=text(UiStrings.t("分享名片"),19,theme.text);title.setTypeface(null,1);header.addView(title,new LinearLayout.LayoutParams(0,-2,1));header.addView(button("✕",dialog::dismiss,false),new LinearLayout.LayoutParams(dp(38),dp(38)));add(content,header);
        HorizontalScrollView formatScroll=new HorizontalScrollView(activity);formatScroll.setHorizontalScrollBarEnabled(false);LinearLayout formatRow=row();formatScroll.addView(formatRow);String[] labels={"X · 链结预览 1.91:1","IG 贴文 1:1","IG 直式 4:5","限时动态 9:16"};for(int i=0;i<labels.length;i++){String choice=ShareCardRenderer.FORMATS[i];Button option=button(UiStrings.t(labels[i]),()->{if(saveTask!=null){handler.removeCallbacks(saveTask);saveTask.run();}format=choice;drawControls();},format.equals(choice));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-2,dp(36));p.rightMargin=dp(5);formatRow.addView(option,p);}add(content,formatScroll);
        preview=new ImageView(activity);preview.setAdjustViewBounds(true);preview.setScaleType(ImageView.ScaleType.FIT_CENTER);preview.setBackground(round(theme.surface2,12));add(content,preview);status=text("",11,theme.muted);add(content,status);preview();
        section(UiStrings.t("风格"));LinearLayout styles=row();String[] styleLabels={"海报","资料卡","大字","夜色","极简"};for(int i=0;i<styleLabels.length;i++){String style=ShareCardRenderer.STYLES[i];Button option=button(UiStrings.t(styleLabels[i]),()->{config().style=style;changed();drawControls();},style.equals(config().style));styles.addView(option,new LinearLayout.LayoutParams(0,dp(35),1));}add(content,styles);
        section(UiStrings.t("配色"));LinearLayout palettes=row();for(int i=0;i<ShareCardRenderer.PALETTES.length;i++){String value=ShareCardRenderer.PALETTES[i];View circle=new View(activity);GradientDrawable color=round(ShareCardRenderer.COLORS[i],20);if(value.equals(config().palette))color.setStroke(dp(3),Color.WHITE);circle.setBackground(color);circle.setContentDescription(UiStrings.t("配色")+" "+value);circle.setFocusable(true);circle.setOnClickListener(v->{config().palette=value;changed();drawControls();});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(dp(31),dp(31));p.rightMargin=dp(10);palettes.addView(circle,p);}add(content,palettes);
        section(UiStrings.t("照片"));FlowLayout photosView=new FlowLayout(activity);for(JSONObject photo:photos){String id=photo.optString("id");ImageView thumb=new ImageView(activity);thumb.setScaleType(ImageView.ScaleType.CENTER_CROP);thumb.setBackground(round(theme.surface2,8));api.image(thumb,photo,true);if(id.equals(photoId())){GradientDrawable border=round(theme.accent,8);border.setStroke(dp(2),theme.accent);thumb.setBackground(border);}thumb.setContentDescription(UiStrings.t("选择照片")+" "+id);thumb.setOnClickListener(v->{config().photoId=id;changed();drawControls();});photosView.addView(thumb,new android.view.ViewGroup.LayoutParams(dp(55),dp(55)));}add(content,photosView);
        section(UiStrings.t("卡片上放的资料"));FlowLayout fields=new FlowLayout(activity);for(int i=0;i<ShareCardRenderer.FIELDS.length;i++){String field=ShareCardRenderer.FIELDS[i];Button toggle=button((config().fields.contains(field)?"✓ ":"")+UiStrings.t(ShareCardRenderer.FIELD_LABELS[i]),()->{if(!config().fields.add(field))config().fields.remove(field);changed();drawControls();},config().fields.contains(field));fields.addView(toggle);}add(content,fields);
        section(UiStrings.t("加一句话"));EditText note=new EditText(activity);note.setSingleLine(true);note.setTextColor(theme.text);note.setHintTextColor(theme.muted);note.setTextSize(13);note.setHint(UiStrings.t("例如：周末晚上一起玩"));note.setFilters(new InputFilter[]{new InputFilter.LengthFilter(60)});note.setText(config().text);note.setBackground(round(theme.surface2,10));note.setPadding(dp(12),dp(9),dp(12),dp(9));add(content,note);note.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int start,int count,int after){}public void onTextChanged(CharSequence s,int start,int before,int count){config().text=s.toString();changed();}public void afterTextChanged(Editable e){}});TextView counter=text(config().text.length()+"/60",11,theme.muted);add(content,counter);note.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int start,int count,int after){}public void onTextChanged(CharSequence s,int start,int before,int count){counter.setText(s.length()+"/60");}public void afterTextChanged(Editable e){}});
        boolean member=me.optJSONObject("membership")!=null&&me.optJSONObject("membership").optInt("rank")>0;Switch brand=new Switch(activity);brand.setText(UiStrings.t("网站标识"));brand.setTextColor(theme.text);brand.setChecked(config().brand||!member);brand.setEnabled(member);brand.setOnCheckedChangeListener((v,on)->{config().brand=on;changed();});add(content,brand);if(!member)add(content,text(UiStrings.t("会员可以关闭网站标识"),11,theme.muted));Switch invite=new Switch(activity);invite.setText(UiStrings.t("连结带上我的邀请码"));invite.setTextColor(theme.text);invite.setChecked(config().invite);invite.setOnCheckedChangeListener((v,on)->{config().invite=on;changed();});add(content,invite);
        LinearLayout actionsRow=row();String[] names={"下载图片","分享","发到 X"};for(int i=0;i<names.length;i++){final int action=i;Button b=button(UiStrings.t(names[i]),()->{if(action==2){actions.postX(url());return;}byte[] png=png();if(png==null)return;if(action==0)actions.save(png);else actions.share(png,url());},i==0);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(42),1);p.rightMargin=dp(5);actionsRow.addView(b,p);}add(content,actionsRow);
        LinearLayout secondary=row();String[] other={"复制图片","复制连结"};for(int i=0;i<2;i++){final int action=i;Button b=button(UiStrings.t(other[i]),()->{if(action==0){byte[] png=png();if(png!=null)actions.copy(png);}else actions.copyLink(url());},false);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(38),1);p.rightMargin=dp(5);secondary.addView(b,p);}add(content,secondary);if(format.equals("og"))add(content,button(UiStrings.t("设为连结预览图"),()->{byte[] png=png();if(png!=null)actions.setPreview(png);},false));
    }
    private void preview(){if(preview==null||profile==null)return;String photo=photoId();if(!photo.isEmpty()&&!images.containsKey(photo)&&triedPhotos.add(photo)){status.setText(UiStrings.t("正在加载照片…"));api.shareCardPhoto(photo,bitmap->{if(!dialog.isShowing())return;images.put(photo,bitmap);preview();});}Bitmap image=images.get(photo);int generation=++renderGeneration;int divisor=format.equals("9x16")?4:3;try{Bitmap rendered=ShareCardRenderer.render(format,config(),profile,image,url(),divisor);if(generation!=renderGeneration){rendered.recycle();return;}android.graphics.drawable.Drawable old=preview.getDrawable();preview.setImageBitmap(rendered);if(old instanceof android.graphics.drawable.BitmapDrawable){Bitmap previous=((android.graphics.drawable.BitmapDrawable)old).getBitmap();if(previous!=rendered&&!previous.isRecycled())previous.recycle();}status.setText(photo.isEmpty()||image!=null?ShareCardRenderer.size(format)[0]+" × "+ShareCardRenderer.size(format)[1]:UiStrings.t(images.containsKey(photo)?"照片加载失败":"正在加载照片…"));}catch(OutOfMemoryError error){status.setText(UiStrings.t("图片过大，无法生成卡片"));}}
    private byte[] png(){String selected=photoId();if(!selected.isEmpty()&&images.get(selected)==null){actions.message(UiStrings.t(images.containsKey(selected)?"照片加载失败":"正在加载照片…"));return null;}try{Bitmap bitmap=ShareCardRenderer.render(format,config(),profile,images.get(selected),url(),1);ByteArrayOutputStream bytes=new ByteArrayOutputStream();bitmap.compress(Bitmap.CompressFormat.PNG,100,bytes);bitmap.recycle();return bytes.toByteArray();}catch(OutOfMemoryError error){actions.message(UiStrings.t("图片过大，无法生成卡片"));return null;}}
}
